/**
  ******************************************************************************
  * @file    sheppard_config.h
  * @brief   Single point of build configuration for the Sheppard firmware.
  *
  * Every compile-time switch that changes measured behaviour lives here, so
  * that one file fully describes the build that produced a dataset. Anything
  * tagged SCIENCE below must be recorded in the record header (TN-16 SS10.5)
  * and frozen across a campaign (TN-16 SS2.1: the clock rate is a science
  * parameter; TN-16 open item 20: -O0 vs -O2 affects SPI timing).
  *
  * This file is NOT generated by CubeMX and will survive regeneration.
  ******************************************************************************
  */

#ifndef SHEPPARD_CONFIG_H
#define SHEPPARD_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

/* ==========================================================================
 * Firmware identity
 * ========================================================================== */

#define SHEPPARD_FW_NAME            "sheppard"
#define SHEPPARD_FW_VERSION_MAJOR   0
#define SHEPPARD_FW_VERSION_MINOR   2
#define SHEPPARD_FW_VERSION_PATCH   17
#define SHEPPARD_FW_VERSION_STR     "0.2.17"

/* OPTIMISATION LEVEL IS A SCIENCE PARAMETER -- TN-16 open item 20.
 * Frozen at -Os from 28 July 2026, tag Stage-B-chained-dma-Os onwards. All
 * bring-up data before this (V0.4, M1, the drift runs) was taken at -O0.
 * The original concern was SPI timing; with the transfers now driven by DMA
 * that is hardware-determined rather than code-determined, and what remains
 * is ISR latency (a fixed, calibratable offset) and bus duty cycle, which
 * rule R8 already controls as a confound. Do not change it again mid-campaign
 * -- doing so splits the dataset. */
#define SHEPPARD_OPT_LEVEL          "-Os"

/* Free-text build tag. Change this when the build differs in any way that
   could touch the data, and log it in every record header. */
#define SHEPPARD_BUILD_TAG          "Stage-D-charger-autorun-Os"

/* Directory holding records on the card. One definition, used by both the
   writer and the download commands. */
#define SHEPPARD_SD_DIR             "SHEPPARD"

/* SPI SCK frequency, forced identically on every slot by bus_init().
   THIS IS A SCIENCE PARAMETER. Rule R8 (TN-14 section 6) controls bus activity
   as a confound, so the two specimens must be read over identical buses; before
   28 July slot 2 ran at 16 MHz against slot 1's 8 MHz because SPI3 sits on APB1
   with a different CubeMX prescaler, which would have written a bus-rate
   difference straight into the specimen axis. The ICM-42688-P permits 24 MHz
   (DS-000347 section 10.2); 8 MHz is chosen low to limit switching noise, in
   the same spirit as the 32 MHz SYSCLK. */
#define SHEPPARD_SPI_HZ             8000000UL

/* LED drive polarity. 1 = the pin sinks the cathode, so RESET lights the LED.
   If the indicators come out inverted after flashing -- breathing when they
   should be dark, dark while recording -- flip this and nothing else. */
#define SHEPPARD_LED_ACTIVE_LOW     0

/* ==========================================================================
 * Flash layout
 *
 * STAGE 1 (this build): application linked at the reset vector, flashed by
 *   ST-LINK. No bootloader present. SHEPPARD_APP_BASE must equal
 *   ORIGIN(FLASH) in STM32F723ZETX_FLASH.ld.
 *
 * STAGE 2 (after the DFU loader exists): set SHEPPARD_APP_BASE to 0x08010000,
 *   change ORIGIN(FLASH) in the linker script to match, and leave
 *   SHEPPARD_VTOR_RELOCATE at 1. Nothing else in the application changes.
 *
 * [verify] The 0x08010000 boundary assumes the STM32F723ZE 512 KiB flash is
 * organised 4 x 16 KiB, 1 x 64 KiB, 3 x 128 KiB, making 0x08010000 the start
 * of sector 4. CONFIRM AGAINST RM0431 TABLE "Flash module organization"
 * BEFORE BUILDING THE LOADER -- the loader's sector-erase table depends on
 * the same numbers, and an over-erase takes the loader out with it.
 * ========================================================================== */

#define SHEPPARD_APP_BASE           0x08000000UL
#define SHEPPARD_VTOR_RELOCATE      1     /* harmless when APP_BASE is 0x08000000 */

/* ==========================================================================
 * Console
 *
 * CDC is the primary console. USART1 (PA9/PA10) is a compile-time mirror.
 *
 * NOTE ON THE DEFAULT: you asked for the UART mirror to be opt-in. It ships
 * ENABLED because TN-16 SS3.1 and SS7.3 both depend on it -- USART1 is the only
 * channel that produces output before enumeration, when a charge-only cable
 * is fitted, or when the USB stack itself is the fault. Set it to 0 for
 * science builds, where TN-16 SS7.4 requires USB disconnected anyway and the
 * extra GPIO switching is unwanted.
 * ========================================================================== */

#define SHEPPARD_CONSOLE_CDC            1
#define SHEPPARD_CONSOLE_UART_MIRROR    1     /* -> 0 for science builds */

#define SHEPPARD_CONSOLE_LINE_MAX       96U   /* longest accepted input line   */
#define SHEPPARD_CONSOLE_TX_MAX        192U   /* longest single printf output  */
#define SHEPPARD_CONSOLE_RX_RING       256U   /* must be a power of two        */
#define SHEPPARD_CONSOLE_MAX_CMD_SETS     8U  /* modules that may register cmds */

#define SHEPPARD_CONSOLE_UART_TIMEOUT_MS 100U
#define SHEPPARD_CONSOLE_CDC_TIMEOUT_MS  100U /* host not draining -> give up  */

/* Echo typed characters back to the CDC host. Tera Term has no local echo by
   default, so without this you type blind. Costs one extra CDC transfer per
   keystroke, which only matters while a human is typing. */
#define SHEPPARD_CONSOLE_ECHO           1

/* ==========================================================================
 * USB
 * ========================================================================== */

/* Advertise a DFU run-time interface alongside CDC (composite, IAD-grouped).
 *
 * OFF. Firmware update is done by the self-flasher in fwupdate.c over the
 * CDC endpoints, so a DFU interface has nothing to talk to: a host that
 * issued DFU_DETACH would only reboot the application into itself. Setting
 * this to 0 compiles out the DFU state machine and the 18 descriptor bytes
 * entirely.
 *
 * The composite wrapper itself is retained. With DFU off it serves a plain
 * two-interface CDC configuration that happens to carry an IAD -- about 180
 * bytes of flash over the stock class, no runtime cost. Kept because
 * reverting to the stock CDC descriptor would re-risk an enumeration path
 * that is already tested and working, and because a resident DFU loader is
 * then one #define away if the self-flasher's lack of automatic recovery
 * ever becomes a problem.
 */
#define SHEPPARD_USB_DFU_RUNTIME        0

/* USB interface numbers. CDC must be 0 and 1 and must be contiguous, because
   the IAD groups them. */
#define SHEPPARD_ITF_CDC_COMM           0U
#define SHEPPARD_ITF_CDC_DATA           1U
#define SHEPPARD_ITF_DFU                2U
#define SHEPPARD_ITF_COUNT              3U

/* DFU functional descriptor fields.
   bcdDFUVersion 0x011A selects ST's DfuSe variant, which is what
   STM32CubeProgrammer expects. Plain DFU 1.1 would be 0x0110.
   [verify] whether CubeProgrammer honours a run-time DFU interface at all --
   see TN-17 SS4. Nothing critical depends on it; the `dfu` console command is
   the guaranteed path into the loader. */
#define SHEPPARD_DFU_DETACH_TIMEOUT_MS  255U
#define SHEPPARD_DFU_TRANSFER_SIZE      1024U
#define SHEPPARD_DFU_BCD_VERSION        0x011AU

/* Grace period between acknowledging DFU_DETACH (or the `dfu` command) and
   pulling the reset, so the host sees the control transfer complete and the
   console line is flushed. */
#define SHEPPARD_DFU_DETACH_GRACE_MS    50U

/* ==========================================================================
 * Self-flasher (fwupdate.c)
 *
 * The application receives a new image over its own CDC endpoints, stages it
 * in SRAM, verifies it, then jumps to a routine in RAM that mass-erases the
 * flash and reprograms it from the staging buffer, and resets.
 *
 * WHY IT HAS TO WORK THIS WAY
 *   On single-bank F7 flash, any read of the array during a program or erase
 *   stalls the bus, so the erase/program loop cannot be fetching instructions
 *   from the flash it is erasing. Hence the routine lives in .RamFunc and
 *   the whole image is buffered before a single byte is erased.
 *
 * WHAT IT CANNOT DO
 *   The flasher is part of the image it replaces. A successfully written but
 *   non-running application takes the flasher with it, and recovery is via
 *   ST-LINK. That is the price of not having a resident loader.
 *
 * MASS ERASE, NOT SECTOR ERASE
 *   Deliberate: it removes any dependence on the STM32F723ZE sector map,
 *   which is still unconfirmed against RM0431. There is nothing else in
 *   flash worth preserving. Costs a few seconds per update.
 * ========================================================================== */

#define SHEPPARD_FW_UPDATE              1

/* ==========================================================================
 * Storage (storage.c)
 * ========================================================================== */

/* How often the FAT is updated during a record.
 *
 * NOT per block. A truncated record is scientifically void anyway -- R2's
 * thermal gate and the uniform-sampling assumption behind Allan variance both
 * fail on a partial capture -- so per-block durability buys little, while a
 * FAT update 40 times a second at ODR 8000 is exactly the operation TN-16
 * section 6.4 warns produces stalls of tens to hundreds of ms.
 *
 * 30 s bounds the DIAGNOSTIC loss: block sequence numbers and timestamps say
 * when and why an unattended run died. storage_get_stats() times f_sync
 * separately from f_write so this can be revisited from measurement rather
 * than argument. */
#define SHEPPARD_SD_SYNC_MS             30000U

/* FIFO watermark policy, in the absence of an explicit per-record override.
 *
 * Derived, not chosen:
 *   - rule R8 requires the watermark to be changeable 4x at fixed ODR, so it
 *     must be a per-record field regardless
 *   - TN-16 section 9.6 rules out per-sample interrupts at ODR 8000
 *   - the FIFO is 2 KiB, so the cap must leave headroom for service latency
 *
 * Target ~100 ms of samples, capped at 1000 B (50 packets). Gives 3 packets
 * at 25 Hz and 50 at 8 kHz, i.e. 160 IRQ/s at the top rate. The cap is 49% of
 * the FIFO, leaving 6.4 ms of overflow tolerance at 8 kHz against a ~1 ms
 * DMA read. */
#define SHEPPARD_WM_TARGET_MS           100U
#define SHEPPARD_WM_MAX_BYTES           1000U

/* Staging buffer, in .bss. Must exceed the largest image you will flash.
   If the link fails with "region RAM overflowed", reduce this. The `fw`
   command reports the limit and refuses anything larger.

   REDUCED 160 -> 128 KiB on 27 Jul 2026. The linker split moved .bss out of
   DTCM into the 192 KiB SRAM1+SRAM2 region, so the budget is 192 KiB rather
   than 256 KiB. At a ~73 KiB image, 128 KiB is still 1.75x headroom.

   This is an interim measure. The real fix is a single shared arena: the
   staging buffer and the sampler's DMA ring are never in use at the same
   time -- you do not flash mid-record -- so they should overlay each other
   with a runtime guard. Due in Stage B, once the SD stall measurement fixes
   the ring size (TN-18 section 5, TN-16 open item 7). */
#define SHEPPARD_FW_STAGE_SIZE          (128U * 1024U)

/* Smallest plausible image. Guards against a typo'd size erasing the part. */
#define SHEPPARD_FW_MIN_SIZE            (2U * 1024U)

/* Abort and return to the console if the transfer stalls for this long. */
#define SHEPPARD_FW_RX_TIMEOUT_MS       5000U

/* Delay between the last console line and pulling the trigger, so the host
   sees the confirmation before the USB device disappears. */
#define SHEPPARD_FW_PROGRAM_DELAY_MS    250U

/* ==========================================================================
 * Boot control (backup-register protocol shared with the loader)
 *
 * DR0 is already taken by the RTC set-once marker (TN-16 SS8.2). Do not reuse.
 *
 * CAVEAT: backup-domain contents survive a reset but only survive a power
 * cycle if VBAT has its own cell -- TN-16 open item 17, still unresolved. The
 * failed-boot counter is therefore reliable for the case that matters (an app
 * just flashed over USB that will not run) and unreliable across power-off.
 * ========================================================================== */

#define SHEPPARD_BKP_RTC_MAGIC          RTC_BKP_DR0   /* owned by rtc_init_once */
#define SHEPPARD_BKP_BOOT_REQ           RTC_BKP_DR1
#define SHEPPARD_BKP_BOOT_ATTEMPTS      RTC_BKP_DR2

#define SHEPPARD_BOOT_REQ_DFU           0x44465521UL  /* 'DFU!' */
#define SHEPPARD_BOOT_REQ_NONE          0x00000000UL

/* Consecutive failed boots before the loader refuses to jump and stays in DFU. */
#define SHEPPARD_BOOT_MAX_ATTEMPTS      3U

/* Uptime after which the application declares itself healthy and clears the
   attempt counter. Long enough to have finished peripheral init and entered
   the main loop; short enough not to annoy. */
#define SHEPPARD_BOOT_HEALTHY_MS        3000U

#ifdef __cplusplus
}
#endif

#endif /* SHEPPARD_CONFIG_H */
