/*
 * app.c — minimal bring-up test
 *
 * 1) Reads WHO_AM_I / CHIP_ID from all four sensors over their own SPI bus
 *    and reports pass/fail over UART4 (TX_1/RX_1, J4 header).
 * 2) Toggles all four LEDs at four different, octave-spaced rates using
 *    HAL_GetTick() (SysTick-derived ms timebase) so a working/incorrect
 *    clock tree is immediately visible by eye (each LED should blink at
 *    exactly half the rate of the previous one).
 *
 * PREREQUISITES IN main.c (all should already exist from CubeMX generation):
 *   - hspi1, hspi3, hspi4, hspi5   (SPI handles)
 *   - huart4                       (UART4 handle, TX_1/RX_1)
 *   - CS_1_Pin/GPIO_Port ... CS_4_Pin/GPIO_Port   (from GPIO_Label "CS_n")
 *   - LED_1_Pin/GPIO_Port ... LED_4_Pin/GPIO_Port (from GPIO_Label "LED_n")
 * These macros are auto-generated by CubeMX in main.h from the pin labels
 * already present in the .ioc, so no extra CubeMX config is needed for
 * WHO_AM_I. The LED section only needs SPI + UART4 + GPIO, already present.
 *
 * NOT using TIM2 here on purpose: TIM2 is not yet enabled in the .ioc.
 * HAL_GetTick() (1 ms SysTick) is sufficient to prove the clock tree/timebase
 * for this bring-up check. Swap to TIM2->CNT later once TIM2 is added, for
 * microsecond-resolution timestamping during real captures.
 */

#include "app.h"
#include <stdio.h>
#include <string.h>

extern SPI_HandleTypeDef  hspi1;   /* ICM-42688-P #1 */
extern SPI_HandleTypeDef  hspi3;   /* ICM-42688-P #2 */
extern SPI_HandleTypeDef  hspi4;   /* BMI323          */
extern SPI_HandleTypeDef  hspi5;   /* ISM330DHCX       */
extern UART_HandleTypeDef huart4;  /* debug UART, TX_1/RX_1 */

/* ---- register map (verified against manufacturer datasheets) ---- */
#define ICM42688_REG_WHO_AM_I   0x75u
#define ICM42688_WHO_AM_I_VAL   0x47u

#define ISM330_REG_WHO_AM_I     0x0Fu
#define ISM330_WHO_AM_I_VAL     0x6Bu

#define BMI323_REG_CHIP_ID      0x00u
#define BMI323_CHIP_ID_VAL      0x43u   /* LSB of the 16-bit CHIP_ID word */

#define SPI_READ_BIT            0x80u
#define SPI_TIMEOUT_MS          10u

/* ---------------------------------------------------------------------
 * 8-bit register read: [addr|0x80][dummy] -> rx = [junk][data]
 * Used by both ICM-42688-P instances and the ISM330DHCX (all three use
 * the same 16-clock, no-extra-dummy-byte SPI read protocol).
 * ------------------------------------------------------------------- */
static HAL_StatusTypeDef spi_read_reg8(SPI_HandleTypeDef *hspi,
                                        GPIO_TypeDef *cs_port, uint16_t cs_pin,
                                        uint8_t reg, uint8_t *out)
{
    uint8_t tx[2] = { (uint8_t)(reg | SPI_READ_BIT), 0x00u };
    uint8_t rx[2] = { 0 };
    HAL_StatusTypeDef st;

    HAL_GPIO_WritePin(cs_port, cs_pin, GPIO_PIN_RESET);
    st = HAL_SPI_TransmitReceive(hspi, tx, rx, sizeof(tx), SPI_TIMEOUT_MS);
    HAL_GPIO_WritePin(cs_port, cs_pin, GPIO_PIN_SET);

    *out = rx[1];
    return st;
}

/* ---------------------------------------------------------------------
 * BMI323 CHIP_ID read: 16-bit register, [addr|0x80][dummy][data_L][data_H]
 *
 * CAUTION — VERIFY ON FIRST BRING-UP: the datasheet explicitly documents
 * 2 dummy bytes for the I3C protocol; this uses 1 dummy byte per the SPI
 * convention used elsewhere in the Bosch BMI/BMA family (and your own
 * TN open item #21). If chip_id_lsb reads back as 0x00 or garbage, scope
 * the transaction and try 2 dummy bytes (5-byte total transfer) instead.
 * ------------------------------------------------------------------- */
static HAL_StatusTypeDef bmi323_read_chipid(SPI_HandleTypeDef *hspi,
                                             GPIO_TypeDef *cs_port, uint16_t cs_pin,
                                             uint8_t *chip_id_lsb)
{
    uint8_t tx[4] = { (uint8_t)(BMI323_REG_CHIP_ID | SPI_READ_BIT), 0x00u, 0x00u, 0x00u };
    uint8_t rx[4] = { 0 };
    HAL_StatusTypeDef st;

    HAL_GPIO_WritePin(cs_port, cs_pin, GPIO_PIN_RESET);
    st = HAL_SPI_TransmitReceive(hspi, tx, rx, sizeof(tx), SPI_TIMEOUT_MS);
    HAL_GPIO_WritePin(cs_port, cs_pin, GPIO_PIN_SET);

    *chip_id_lsb = rx[2];   /* rx[0]=junk (during addr byte), rx[1]=dummy, rx[2]=data_L */
    return st;
}

static void uart_report(const char *sensor_name, uint8_t got, uint8_t expected, HAL_StatusTypeDef st)
{
    char msg[72];
    int ok = (st == HAL_OK) && (got == expected);
    int n = snprintf(msg, sizeof(msg), "%-16s got=0x%02X exp=0x%02X %s\r\n",
                      sensor_name, got, expected, ok ? "PASS" : "FAIL");
    if (n > 0) {
        HAL_UART_Transmit(&huart4, (uint8_t *)msg, (uint16_t)n, 100);
    }
}

/* ---------------------------------------------------------------------
 * LED blink bookkeeping — 4 independent, non-blocking, octave-spaced
 * toggle rates so a correct clock/timebase is visually obvious:
 *   LED_1 toggles every  250 ms -> 2 Hz blink
 *   LED_2 toggles every  500 ms -> 1 Hz blink
 *   LED_3 toggles every 1000 ms -> 0.5 Hz blink
 *   LED_4 toggles every 2000 ms -> 0.25 Hz blink
 * Each LED should blink at exactly half the rate of the one before it;
 * any drift away from that ratio flags a clock-tree misconfiguration
 * immediately, without needing a scope.
 * ------------------------------------------------------------------- */
typedef struct {
    GPIO_TypeDef *port;
    uint16_t      pin;
    uint32_t      period_ms;
    uint32_t      last_toggle_ms;
} led_blinker_t;

static led_blinker_t s_leds[4];

void App_Init(void)
{
    uint8_t id;
    HAL_StatusTypeDef st;

    /* small settle delay after power/reset before first SPI transaction */
    HAL_Delay(10);

    st = spi_read_reg8(&hspi1, CS_1_GPIO_Port, CS_1_Pin, ICM42688_REG_WHO_AM_I, &id);
    uart_report("ICM#1 (SPI1)", id, ICM42688_WHO_AM_I_VAL, st);

    st = spi_read_reg8(&hspi3, CS_2_GPIO_Port, CS_2_Pin, ICM42688_REG_WHO_AM_I, &id);
    uart_report("ICM#2 (SPI3)", id, ICM42688_WHO_AM_I_VAL, st);

    st = spi_read_reg8(&hspi5, CS_3_GPIO_Port, CS_3_Pin, ISM330_REG_WHO_AM_I, &id);
    uart_report("ISM330 (SPI5)", id, ISM330_WHO_AM_I_VAL, st);

    st = bmi323_read_chipid(&hspi4, CS_4_GPIO_Port, CS_4_Pin, &id);
    uart_report("BMI323 (SPI4)", id, BMI323_CHIP_ID_VAL, st);

    /* LED schedule */
    uint32_t now = HAL_GetTick();
    s_leds[0] = (led_blinker_t){ LED_1_GPIO_Port, LED_1_Pin,  250u, now };
    s_leds[1] = (led_blinker_t){ LED_2_GPIO_Port, LED_2_Pin,  500u, now };
    s_leds[2] = (led_blinker_t){ LED_3_GPIO_Port, LED_3_Pin, 1000u, now };
    s_leds[3] = (led_blinker_t){ LED_4_GPIO_Port, LED_4_Pin, 2000u, now };
}

void App_Run(void)
{
    uint32_t now = HAL_GetTick();
    for (int i = 0; i < 4; i++) {
        if ((uint32_t)(now - s_leds[i].last_toggle_ms) >= s_leds[i].period_ms) {
            HAL_GPIO_TogglePin(s_leds[i].port, s_leds[i].pin);
            s_leds[i].last_toggle_ms = now;
        }
    }
}
